### ISSUE TITLE
Publish to open-vsx

### ISSUE THREAD

**Issue by saibotk** [WilliamVenner/vscode-glua-enhanced#17]
Thank you for the awesome project!

I just wanted to kindly ask if you want to publish the add-on to the https://open-vsx.org/ repository. As this is an open alternative, that is used by default for open source builds of vscode (usually found as code on most Linux distributions). So it is available for them too, without installing it manually.

Keep up the cool work :rocket:

**Comment by WilliamVenner** [comment]
Done, thank you

https://open-vsx.org/extension/venner/vscode-glua-enhanced

**Comment by WilliamVenner** [comment]
Not sure if it's just cached, but it appears to be on version 0.2.0. I have uploaded version 2.1.1 and it's showing this in the search, but not on the actual extension listing page. So give it a few if you find the alpha version installed to your VSCode :)

**Comment by saibotk** [comment]
Wow, that was fast!
Thank you very very much :+1:
