### ISSUE TITLE
Remote-SSH Connection Closed When Extension is Enabled

### ISSUE THREAD

**Issue by jellyton69** [WilliamVenner/vscode-glua-enhanced#18]
If this extension is enabled in a Code window that's connected to a server via SSH, the window will disconnect after ~20 seconds, every time. Once it's disabled, the disconnects stop. It works fine in a local window.

**Comment by nodgear** [comment]
Tested, doesn't happen with me.
Windows 10 x64
VSCode server (linux)
Microsoft vscode remove extension pack (SSH -> VSCServer)

**Comment by WilliamVenner** [comment]
I can actually reproduce this. However I get a completely useless stack trace that I'm not really sure what to do with.

https://github.com/microsoft/vscode-remote-release/issues/4785

**Comment by WilliamVenner** [comment]
Should be fixed in 2.3.2.
