### ISSUE TITLE
Code analysis (find globals) fails to work under WSL

### ISSUE THREAD

**Issue by chelog** [WilliamVenner/vscode-glua-enhanced#20]
Hey there. I'm pretty new to WSL stuff however I developed under both Unix and Windows systems. I set up fresh WSL build and set up server, everything works fine (including all other extensions) except the globals scan. VSCode ceases to autocomplete global tables under WSL, but working under plain Windows just fine. If you need any additional reports, I would gladly send them if you tell me where to look

![](https://i.imgur.com/9CQ9WH8.png)
![](https://i.imgur.com/9L3naIb.png)

My setup: WSL2 running Ubuntu 20.04, host is Windows 10 build 19042, VSCode:
![](https://i.imgur.com/HxlGSaD.png)

**Comment by WilliamVenner** [comment]
Huh? Does WSL have anything to do with this? Is VSCode running on Windows, but the files you're editing on the WSL filesystem?

**Comment by chelog** [comment]
@WilliamVenner yes, my gmod server is fully installed into Linux under WSL2. VSCode client is running in host Windows connected to VSCode server in WSL. You need to install some extensions into VSCode server under WSL, like this:
![](https://i.imgur.com/Yn1eVL3.png)

I think it has something to do with gluadump not being able to properly list and read files that are located in WSL filesystem

**Comment by chelog** [comment]
Just found the article in VS docs that may help to solve this:
https://code.visualstudio.com/api/advanced-topics/remote-extensions

**Comment by WilliamVenner** [comment]
I believe this should be fixed in 2.3.2.

**Comment by chelog** [comment]
@WilliamVenner I can confirm that extension is now up and running in WSL fixing the "does not exist" error. However, dump isn't working still I guess:

![](https://i.imgur.com/3auvev4.png)
![](https://i.imgur.com/h7HUCc6.png)
