### ISSUE TITLE
Support VSCode - Better Comments

### ISSUE THREAD

**Issue by NickMlynek** [WilliamVenner/vscode-glua-enhanced#35]
It would be nice if we could use https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments, but currently the inline comments are not working in combination with your extension.

![image](https://user-images.githubusercontent.com/73931823/133888298-003f8f9c-1ff7-4c39-ae75-e9b3bbe62650.png)

**Comment by WilliamVenner** [comment]
It would appear that the extension is hard coded to Lua support.

https://github.com/aaron-bond/better-comments/blob/master/src/parser.ts#L339

GLua has C-styled comments as an addition from Garry. They do not exist in normal Lua.

**Comment by NickMlynek** [comment]
I see ... to bad, the comments would be really helpful, but still thanks for looking into it.
Keep up the good work!
