### ISSUE TITLE
IntelliSense not working

### ISSUE THREAD

**Issue by ALENI27** [WilliamVenner/vscode-glua-enhanced#36]
I am on windows 10. I use vs code 1.60.2
I followed this: https://wiki.facepunch.com/gmod/Lua_Editors to setup everything (the vs code part).
When I try to autocomplete, intelliSense give me that kind of things.
![image](https://user-images.githubusercontent.com/48592390/135869038-a6d422a9-5588-46cf-9c27-4d10c9df58a9.png)
It does not even recognise the 'ply' (sometimes it does, it's random.).
I already tried to change some editor settings in the "settings.json" but nothing worked.
It event gives me unrelated things (see bellow).
![image](https://user-images.githubusercontent.com/48592390/135870531-30cf9c4e-73f7-436d-b17e-357723d9c7ca.png)

**Comment by WilliamVenner** [comment]
Do you have something else installed that is overriding it

**Comment by ALENI27** [comment]
I just have the ones listed on the gmod wiki, I already tried to uninstall all the others.

**Comment by WilliamVenner** [comment]
What you are seeing here are snippets provided by another extension. My extension does not provide these snippets. I think you have another glua extension installed.

**Comment by ALENI27** [comment]
If I disable the others extensions listed of the wiki it's even worse, now it does not work at all, I have just random things not related at all with what I typed.

**Comment by WilliamVenner** [comment]
What do you see

**Comment by ALENI27** [comment]
If I only use GLua Enhanced I see that
![image](https://user-images.githubusercontent.com/48592390/136018472-5baed6d0-6fe5-45ba-89a0-5cc59d71d2c0.png)

**Comment by ALENI27** [comment]
Yes it is, that the problem.
![image](https://user-images.githubusercontent.com/48592390/136060705-efd224b5-b4f5-4edd-a2f0-498047334e7c.png)

**Comment by WilliamVenner** [comment]
Change the language to "GLua" in the bottom right of VSCode.

**Comment by ALENI27** [comment]
It's already in "GLua"

**Comment by ALENI27** [comment]
if I go with 2 dot, that random, sometime I have that.
![image](https://user-images.githubusercontent.com/48592390/136072097-6113b674-0e02-45ca-8773-0ad9b0b4d03a.png)
And sometime that.
![image](https://user-images.githubusercontent.com/48592390/136072168-8072cc7e-2a1f-4bc9-adb9-2d6bf77c41a2.png)

**Comment by WilliamVenner** [comment]
This is because VSCode does not always fire the event

**Comment by ALENI27** [comment]
Yes but even when it does, I have everything. I do not have only the things related to (in my case) "Player".

**Comment by WilliamVenner** [comment]
The extension does not provide type inference
