### ISSUE TITLE
Extension host terminated unexpectedly (VS Code 1.73.0)

### ISSUE THREAD

**Issue by WinterPhoenix** [WilliamVenner/vscode-glua-enhanced#44]
Type: <b>Bug</b>

Viewing any GLua file seems to trigger extension host crashes after updating VS Code (technically VSCodium) to 1.73.0

Extension version: 2.5.1
VSCodium version: VSCodium 1.73.0 (6effe8617bbc2e6d2a110c81a5d7d38b141d110d, 2022-11-02T22:41:51.919Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by WilliamVenner** [comment]
Probably gonna need a stack trace or something

**Comment by WinterPhoenix** [comment]
Looks like it was an issue with the Todo Tree extension, that somehow was being triggered by combining with this extension:
https://github.com/Gruntfuggly/todo-tree/issues/692

Everything looks good now, so I'm going to go ahead and close this.
