### ISSUE TITLE
surface.SetDrawColor color picker support

### ISSUE THREAD

**Issue by blobles-dev** [WilliamVenner/vscode-glua-enhanced#5]
Pretty self explanatory. Would be nice to have support for `surface.SetDrawColor(255,0,0)` similar to how `Color(255,0,0)` works.

other notable methods which don't directly use the `Color()` table
- mesh.Color
- render.FogColor
- render.SetShadowColor
- surface.SetTextColor

**Comment by WilliamVenner** [comment]
Also render.Clear

**Comment by WilliamVenner** [comment]
And :SetPlayerColor(Vector(...))
