### ISSUE TITLE
Incorrect work auto completion whith libraries

### ISSUE THREAD

**Issue by Dimasters312** [WilliamVenner/vscode-glua-enhanced#62]
Yesterday everything worked fine, today the libraries auto completion began to work incorrectly.
Auto completion for classes, globals and etc. work fine.
VSCode version: 1.86.1

https://github.com/WilliamVenner/vscode-glua-enhanced/assets/80753616/0b110fb9-e0bc-400f-aebb-510f54ab0f4c

![image](https://github.com/WilliamVenner/vscode-glua-enhanced/assets/80753616/db1e5288-df06-4fb0-a8dd-d6da67bc4ac2)

https://github.com/WilliamVenner/vscode-glua-enhanced/assets/80753616/28d3b756-d421-41d0-8eb1-046d40dc92e9

**Comment by Asra667** [comment]
Same problem

**Comment by WilliamVenner** [comment]
Fixed in 2.5.4
